omarchy-webapp-install "WhatsApp" https://web.whatsapp.com/ WhatsApp.png
omarchy-webapp-install "ChatGPT" https://chatgpt.com/ ChatGPT.png
omarchy-webapp-install "YouTube" https://youtube.com/ YouTube.png
omarchy-webapp-install "GitHub" https://github.com/ GitHub.png
omarchy-webapp-install "Discord" https://discord.com/channels/@me Discord.png
omarchy-webapp-install "Translate" https://translate.google.com/ Translate.png
omarchy-webapp-install "Reddit" https://reddit.com/ Reddit.png
omarchy-webapp-install "Calendar" https://calendar.google.com/calendar/u/0/r/week Calendar.png
omarchy-webapp-install "Graphite" https://app.graphite.dev/ Graphite.png
omarchy-webapp-install "Gmail" https://mail.google.com/mail/u/0/ Gmail.png
