#!/bin/bash
################################################################################
# STEP 3: SYSTEM PREPARATION
################################################################################
#
# Goal: Configure the base system prerequisites before installing packages or
#       drivers. This includes setting up pacman, creating temporary sudo
#       permissions for a smooth installation, disabling disruptive hooks, and
#       installing the core packages required for building AUR packages.
#
run_step_3_prepare_system() {
  log_info "Starting Step 3: System Preparation..."

  # --- Sub-step 3.1: Configure pacman and system repositories ---
  _configure_pacman

  # --- Sub-step 3.2: Configure GPG for pacman keyrings ---
  _configure_system_gpg

  # --- Sub-step 3.3: Set up temporary sudo privileges for first run ---
  _setup_first_run_privileges

  # --- Sub-step 3.4: Temporarily disable mkinitcpio hooks ---
  _disable_mkinitcpio_hooks

  # --- Sub-step 3.5: Install base development tools ---
  _install_base_packages

  # --- Sub-step 3.6: Install AUR helper (yay) ---
  _install_aur_helper

  log_success "Step 3: System Preparation completed."
}

#
# Configures pacman with the Archenemy mirrorlist and installs essential
# build tools. This ensures that the system can fetch packages correctly.
#
_configure_pacman() {
  log_info "Configuring pacman..."
  local PACMAN_CONF_PATH="$ARCHENEMY_PATH/default/pacman/pacman.conf"
  local PACMAN_MIRRORLIST_PATH="$ARCHENEMY_PATH/default/pacman/mirrorlist"

  sudo cp -f "$PACMAN_CONF_PATH" /etc/pacman.conf
  sudo cp -f "$PACMAN_MIRRORLIST_PATH" /etc/pacman.d/mirrorlist
  sudo pacman -Syu --noconfirm
}

#
# Configures system-wide GPG to ensure pacman can correctly import and
# verify package signatures. This is crucial for system security and stability.
#
_configure_system_gpg() {
  log_info "Configuring system GPG for pacman..."
  sudo mkdir -p /etc/gnupg
  sudo cp "$ARCHENEMY_PATH/default/gpg/dirmngr.conf" /etc/gnupg/
  sudo chmod 644 /etc/gnupg/dirmngr.conf
  # The following commands from the original script are often unnecessary
  # and can cause issues in automated scripts. Pacman's hooks typically
  # handle the dirmngr restarts when needed.
  # sudo gpgconf --kill dirmngr || true
  # sudo gpgconf --launch dirmngr || true
}

#
# Sets up temporary, passwordless sudo rules for the current user. This allows
# the installer to perform system-wide changes without repeatedly asking for a
# password. These rules are removed at the end of the installation.
#
_setup_first_run_privileges() {
  log_info "Setting up temporary sudo privileges..."
  local sudoers_file="/etc/sudoers.d/archenemy-first-run"
  sudo tee "$sudoers_file" >/dev/null <<EOF
# This file is automatically generated by the Archenemy installer
# and will be removed upon completion.
Cmnd_Alias FIRST_RUN_CLEANUP = /bin/rm -f $sudoers_file
Cmnd_Alias SYMLINK_RESOLVED = /usr/bin/ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
$USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl
$USER ALL=(ALL) NOPASSWD: /usr/bin/ufw
$USER ALL=(ALL) NOPASSWD: /usr/bin/ufw-docker
$USER ALL=(ALL) NOPASSWD: /usr/bin/gtk-update-icon-cache
$USER ALL=(ALL) NOPASSWD: SYMLINK_RESOLVED
$USER ALL=(ALL) NOPASSWD: FIRST_RUN_CLEANUP
EOF
  sudo chmod 440 "$sudoers_file"
}

#
# Temporarily disables the mkinitcpio hooks that run during package
# installations. This prevents multiple, unnecessary initramfs regenerations,
# significantly speeding up the installation process. The hooks are re-enabled
# later, before the final initramfs is built.
#
_disable_mkinitcpio_hooks() {
  log_info "Temporarily disabling mkinitcpio pacman hooks..."
  local install_hook="/usr/share/libalpm/hooks/90-mkinitcpio-install.hook"
  local remove_hook="/usr/share/libalpm/hooks/60-mkinitcpio-remove.hook"

  if [ -f "$install_hook" ]; then
    sudo mv "$install_hook" "${install_hook}.disabled"
  fi

  if [ -f "$remove_hook" ]; then
    sudo mv "$remove_hook" "${remove_hook}.disabled"
  fi
}

#
# Installs the 'base-devel' package group, which contains essential tools
# like make, gcc, and patch, required for building packages, including
# those from the AUR.
#
_install_base_packages() {
  log_info "Installing base development tools..."
  _install_pacman_packages "base-devel"
}

#
# Installs 'yay', a popular AUR helper. This is done by cloning its repository
# and building it using 'makepkg'. This allows the installer to subsequently
# install packages from the Arch User Repository.
#
_install_aur_helper() {
  log_info "Installing AUR helper (yay)..."
  _install_pacman_packages "git"
  local yay_dir="/tmp/yay-install"
  rm -rf "$yay_dir"
  git clone https://aur.archlinux.org/yay.git "$yay_dir"
  (
    cd "$yay_dir" || exit 1
    makepkg -si --noconfirm
  )
  rm -rf "$yay_dir"
}
